Use specific versions of werkzeug and flask.
It looks like a minor/patch update to Werkzeug is responsible for a breaking
change in WFE.

With the exception:

venv/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py:748: in create_scoped_session
    scopefunc = options.pop('scopefunc', _app_ctx_stack.__ident_func__)
E   AttributeError: 'LocalStack' object has no attribute '__ident_func__'
______________ ERROR collecting taskflow/tests/test_lvs_client.py

refs:
https://stackoverflow.com/questions/71695691/flask-app-ctx-stack-ident-func-error-due-to-ident-func-deprecated-in-we
https://github.com/LiniusAustPty/workflow-engine/pull/159
https://linius.slack.com/archives/C02ABE45HHD/p1648657856015249
https://app.circleci.com/pipelines/github/LiniusAustPty/workflow-engine/1376/workflows/f9dc8cab-cb4f-47fe-9214-94688c7163bf/jobs/3591